version: '3.9'

services:
  
  ttl-sync-pre-processor:
    env_file:
      - dev.env
    image: pennsieve/ttl-sync-pre-processor
    volumes:
      - ./data:/service/data
    container_name: ttl-sync-pre-processor
    build:
      context: .
      dockerfile: ./Dockerfile_arm64 # change to Dockerfile on Linux
    entrypoint: /service/main
